browser = edge
name = kunduz
email = imanklv03@gmail.com
gorest.base.url = https://gorest.co.in
bearer.token = e8254c8f2f5cd22dd7b877ab6250e9527a80c9d0687d41a1fb12921ad94be49d
server = localhost
port = 5432
user = postgres